import React from "react";

const TableFreezeTable = () => {
  return (
    <>
      <div className="table-freeze">
        <table className="test">
          <thead>
            <tr>
              <th>#</th>
              <th>Last Name</th>
              <th>First Name</th>
              <th>Middle Initial</th>
              <th>Age</th>
              <th>Birthday</th>
              <th>Address</th>
              <th>Nationality</th>
              <th>Religion</th>
              <th>Educational Attainment</th>
              <th>Current Job Position</th>
              <th>Annual Salary</th>
              <th>Loans</th>
              <th>Accounts</th>
              <th>Current Job Position</th>
              <th>Years of Experience</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>1</td>
              <td>
                Kamote
                KamoteKamoteKamoteKamoteKamoteKamoteKamoteKamoteKamoteKamoteKamote
              </td>
              <td>Kamote</td>
              <td>
                KamoteKamoteKamoteKamoteKamoteKamoteKamoteKamoteKamoteKamoteKamote
              </td>
              <td>Kamote</td>
              <td>Kamote</td>
              <td>Kamote</td>
              <td>Kamote</td>
              <td>Kamote</td>
              <td>Kamote</td>
              <td>Kamote</td>
              <td>Kamote</td>
              <td>Kamote</td>
              <td>Kamote</td>
              <td>Kamote</td>
              <td>Kamote</td>
            </tr>
            <tr>
              <td>2</td>
              <td>Kamote</td>
              <td>Kamote</td>
              <td>Kamote</td>
              <td>Kamote</td>
              <td>Kamote</td>
              <td>Kamote</td>
              <td>Kamote</td>
              <td>Kamote</td>
              <td>Kamote</td>
              <td>Kamote</td>
              <td>Kamote</td>
            </tr>
            <tr>
              <td>3</td>
              <td>Kamote</td>
              <td>Kamote</td>
              <td>Kamote</td>
              <td>Kamote</td>
              <td>Kamote</td>
              <td>Kamote</td>
              <td>Kamote</td>
              <td>Kamote</td>
              <td>Kamote</td>
              <td>Kamote</td>
              <td>Kamote</td>
            </tr>
            <tr>
              <td>4</td>
              <td>Kamote</td>
              <td>Kamote</td>
              <td>Kamote</td>
              <td>Kamote</td>
              <td>Kamote</td>
              <td>Kamote</td>
              <td>Kamote</td>
              <td>Kamote</td>
              <td>Kamote</td>
              <td>Kamote</td>
              <td>Kamote</td>
            </tr>
            <tr>
              <td>5</td>
              <td>Kamote</td>
              <td>Kamote</td>
              <td>Kamote</td>
              <td>Kamote</td>
              <td>Kamote</td>
              <td>Kamote</td>
              <td>Kamote</td>
              <td>Kamote</td>
              <td>Kamote</td>
              <td>Kamote</td>
              <td>Kamote</td>
            </tr>
            <tr>
              <td>6</td>
              <td>Kamote</td>
              <td>Kamote</td>
              <td>Kamote</td>
              <td>Kamote</td>
              <td>Kamote</td>
              <td>Kamote</td>
              <td>Kamote</td>
              <td>Kamote</td>
              <td>Kamote</td>
              <td>Kamote</td>
              <td>Kamote</td>
            </tr>
            <tr>
              <td>7</td>
              <td>Kamote</td>
              <td>Kamote</td>
              <td>Kamote</td>
              <td>Kamote</td>
              <td>Kamote</td>
              <td>Kamote</td>
              <td>Kamote</td>
              <td>Kamote</td>
              <td>Kamote</td>
              <td>Kamote</td>
              <td>Kamote</td>
            </tr>
            <tr>
              <td>8</td>
              <td>Kamote</td>
              <td>Kamote</td>
              <td>Kamote</td>
              <td>Kamote</td>
              <td>Kamote</td>
              <td>Kamote</td>
              <td>Kamote</td>
              <td>Kamote</td>
              <td>Kamote</td>
              <td>Kamote</td>
              <td>Kamote</td>
            </tr>
            <tr>
              <td>9</td>
              <td>Kamote</td>
              <td>Kamote</td>
              <td>Kamote</td>
              <td>Kamote</td>
              <td>Kamote</td>
              <td>Kamote</td>
              <td>Kamote</td>
              <td>Kamote</td>
              <td>Kamote</td>
              <td>Kamote</td>
              <td>Kamote</td>
            </tr>
            <tr>
              <td>10</td>
              <td>Kamote</td>
              <td>Kamote</td>
              <td>Kamote</td>
              <td>Kamote</td>
              <td>Kamote</td>
              <td>Kamote</td>
              <td>Kamote</td>
              <td>Kamote</td>
              <td>Kamote</td>
              <td>Kamote</td>
              <td>Kamote</td>
            </tr>
            <tr>
              <td>11</td>
              <td>Kamote</td>
              <td>Kamote</td>
              <td>Kamote</td>
              <td>Kamote</td>
              <td>Kamote</td>
              <td>Kamote</td>
              <td>Kamote</td>
              <td>Kamote</td>
              <td>Kamote</td>
              <td>Kamote</td>
              <td>Kamote</td>
            </tr>
            <tr>
              <td>12</td>
              <td>Kamote</td>
              <td>Kamote</td>
              <td>Kamote</td>
              <td>Kamote</td>
              <td>Kamote</td>
              <td>Kamote</td>
              <td>Kamote</td>
              <td>Kamote</td>
              <td>Kamote</td>
              <td>Kamote</td>
              <td>Kamote</td>
            </tr>
            <tr>
              <td>13</td>
              <td>Kamote</td>
              <td>Kamote</td>
              <td>Kamote</td>
              <td>Kamote</td>
              <td>Kamote</td>
              <td>Kamote</td>
              <td>Kamote</td>
              <td>Kamote</td>
              <td>Kamote</td>
              <td>Kamote</td>
              <td>Kamote</td>
            </tr>
            <tr>
              <td>14</td>
              <td>Kamote</td>
              <td>Kamote</td>
              <td>Kamote</td>
              <td>Kamote</td>
              <td>Kamote</td>
              <td>Kamote</td>
              <td>Kamote</td>
              <td>Kamote</td>
              <td>Kamote</td>
              <td>Kamote</td>
              <td>Kamote</td>
            </tr>
            <tr>
              <td>15</td>
              <td>Kamote</td>
              <td>Kamote</td>
              <td>Kamote</td>
              <td>Kamote</td>
              <td>Kamote</td>
              <td>Kamote</td>
              <td>Kamote</td>
              <td>Kamote</td>
              <td>Kamote</td>
              <td>Kamote</td>
              <td>Kamote</td>
            </tr>
            <tr>
              <td>16</td>
              <td>Kamote</td>
              <td>Kamote</td>
              <td>Kamote</td>
              <td>Kamote</td>
              <td>Kamote</td>
              <td>Kamote</td>
              <td>Kamote</td>
              <td>Kamote</td>
              <td>Kamote</td>
              <td>Kamote</td>
              <td>Kamote</td>
            </tr>
            <tr>
              <td>17</td>
              <td>Kamote</td>
              <td>Kamote</td>
              <td>Kamote</td>
              <td>Kamote</td>
              <td>Kamote</td>
              <td>Kamote</td>
              <td>Kamote</td>
              <td>Kamote</td>
              <td>Kamote</td>
              <td>Kamote</td>
              <td>Kamote</td>
            </tr>
            <tr>
              <td>18</td>
              <td>Kamote</td>
              <td>Kamote</td>
              <td>Kamote</td>
              <td>Kamote</td>
              <td>Kamote</td>
              <td>Kamote</td>
              <td>Kamote</td>
              <td>Kamote</td>
              <td>Kamote</td>
              <td>Kamote</td>
              <td>Kamote</td>
            </tr>
            <tr>
              <td>19</td>
              <td>Kamote</td>
              <td>Kamote</td>
              <td>Kamote</td>
              <td>Kamote</td>
              <td>Kamote</td>
              <td>Kamote</td>
              <td>Kamote</td>
              <td>Kamote</td>
              <td>Kamote</td>
              <td>Kamote</td>
              <td>Kamote</td>
            </tr>
          </tbody>
        </table>
      </div>
    </>
  );
};

export default TableFreezeTable;
